/* eslint-disable @typescript-eslint/no-misused-promises */
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import Navbar from "~/components/Navbar";

const Home: NextPage = () => {

  const { data: sessionData } = useSession()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col h-[calc(100vh-4rem)] items-center justify-center
        bg-gradient-to-br from-cyan-700 to-lime-400'
      >
        {
          !sessionData && (
            <button className='rounded-full bg-black/10 px-10 py-3 font-semibold
            no-underline transition hover:bg-black/20'
            onClick={sessionData ? () => signOut() : () => signIn('google')}
            >
              Sign in with Google
            </button>
          )
        }

      </main>
      <Navbar />
    </>
  );
};

export default Home;

